FROM centos:7.9.2009

ARG gcc_version=4.9-2016.02
ENV GCC_VERSION $gcc_version

# Install requirements
RUN yum install -y \
	apr-devel \
	autoconf \
	automake \
	git \
	glibc-devel \
	libaio-devel \
	libtool \
	lksctp-tools \
	make \
	openssl-devel \
	redhat-lsb-core \
	tar \
	wget

# Install Java
RUN yum install -y java-1.8.0-openjdk-devel

# Install aarch64 gcc toolchain
RUN set -x && \
  wget https://releases.linaro.org/components/toolchain/binaries/$GCC_VERSION/aarch64-linux-gnu/gcc-linaro-$GCC_VERSION-x86_64_aarch64-linux-gnu.tar.xz && \
  tar xvf gcc-linaro-$GCC_VERSION-x86_64_aarch64-linux-gnu.tar.xz

ENV PATH="/gcc-linaro-$GCC_VERSION-x86_64_aarch64-linux-gnu/bin:${PATH}"
ENV JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk/"
