version: "3"

services:

  runtime-setup:
    image: netty-io_uring:default
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos6

  common: &common
    image: netty-io_uring:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
    working_dir: /code

  test-leak:
    <<: *common
    command: /bin/bash -cl "mvn -Pleak clean test -Dio.netty.testsuite.badHost=netty.io"

  test:
    <<: *common
    command: /bin/bash -cl "mvn clean test -Dio.netty.testsuite.badHost=netty.io"

  build: 
    <<: *common
    command: /bin/bash -cl "mvn clean package -Dio.netty.testsuite.badHost=netty.io"

  shell:
    <<: *common
    environment:
      - SONATYPE_USER
      - SONATYPE_PASSWORD
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash

  cross-compile-aarch64-runtime-setup:
    image: netty:cross_compile_aarch64
    build:
      context: ../
      dockerfile: docker/Dockerfile.cross_compile_aarch64
      args:
        gcc_version: "4.9-2016.02"

  cross-compile-aarch64-shell:
    image: netty:cross_compile_aarch64
    depends_on: [ cross-compile-aarch64-runtime-setup ]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash
    working_dir: /code

  cross-compile-aarch64-build:
    image: netty:cross_compile_aarch64
    depends_on: [ cross-compile-aarch64-runtime-setup ]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    command: /bin/bash -cl "mvn clean package -Plinux-aarch64"
    working_dir: /code
