FROM centos:7.9.2009

ARG gcc_version=4.9-2016.02
ENV GCC_VERSION $gcc_version

ENV SOURCE_DIR /root/source

# Install requirements
RUN yum install -y \
	apr-devel \
	autoconf \
	automake \
	git \
	glibc-devel \
	libaio-devel \
	libtool \
	lksctp-tools \
	make \
	openssl-devel \
	redhat-lsb-core \
	tar \
	wget

# Install Java
RUN yum install -y java-1.8.0-openjdk-devel

# Install aarch64 gcc toolchain
RUN set -x && \
  wget https://releases.linaro.org/components/toolchain/binaries/$GCC_VERSION/aarch64-linux-gnu/gcc-linaro-$GCC_VERSION-x86_64_aarch64-linux-gnu.tar.xz && \
  tar xvf gcc-linaro-$GCC_VERSION-x86_64_aarch64-linux-gnu.tar.xz

ENV PATH="/gcc-linaro-$GCC_VERSION-x86_64_aarch64-linux-gnu/bin:${PATH}"
ENV JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk/"

WORKDIR /opt
RUN curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar -xz
RUN echo 'PATH=/opt/apache-maven-3.6.3/bin/:$PATH' >> ~/.bashrc

# Prepare our own build
ENV PATH /opt/apache-maven-3.6.3/bin/:$PATH

COPY ./pom.xml $SOURCE_DIR/pom.xml
WORKDIR $SOURCE_DIR
RUN /bin/bash -c 'source $HOME/.bashrc && mvn dependency:go-offline checkstyle:check surefire:test -ntp'
