version: "3"

services:

  cross-compile-aarch64-runtime-setup:
    image: netty-io_uring:cross_compile_aarch64
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos7
      args:
        gcc_version: "4.9-2016.02"
        java_version: "adopt@1.8.0-272"

  cross-compile-aarch64-common: &cross-compile-aarch64-common
    depends_on: [ cross-compile-aarch64-runtime-setup ]
    image: netty-io_uring:cross_compile_aarch64
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ..:/code:delegated
    working_dir: /code

  cross-compile-aarch64-deploy:
    <<: *cross-compile-aarch64-common
    command: /bin/bash -cl "mvn clean deploy -Plinux,linux-aarch64 -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  cross-compile-aarch64-stage-snapshot:
    <<: *cross-compile-aarch64-common
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2:/root/.m2
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "mvn -Plinux,linux-aarch64 clean javadoc:jar package org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true"

  cross-compile-aarch64-stage-release:
    <<: *cross-compile-aarch64-common
    environment:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_PRIVATE_KEY
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.m2:/root/.m2
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "cat <(echo -e \"${GPG_PRIVATE_KEY}\") | gpg --batch --import && mvn -B -Plinux,linux-aarch64 clean javadoc:jar package gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org -DserverId=sonatype-nexus-staging -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.keyname=${GPG_KEYNAME}"

  cross-compile-aarch64-shell:
    <<: *cross-compile-aarch64-common
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash

  cross-compile-aarch64-build:
    <<: *cross-compile-aarch64-common
    command: /bin/bash -cl "mvn clean package -Plinux,linux-aarch64 -DskipTests=true"
