version: "3"

services:

  cross-compile-aarch64-runtime-setup:
    image: netty-io_uring:cross_compile_aarch64
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos7
      args:
        gcc_version: "4.9-2016.02"
        java_version: "adopt@1.8.0-272"

  cross-compile-aarch64-common: &cross-compile-aarch64-common
    depends_on: [ cross-compile-aarch64-runtime-setup ]
    image: netty-io_uring:cross_compile_aarch64
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
    working_dir: /code

  cross-compile-aarch64-deploy:
    <<: *cross-compile-aarch64-common
    command: /bin/bash -cl "mvn clean deploy -Plinux-aarch64 -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  cross-compile-aarch64-shell:
    <<: *cross-compile-aarch64-common
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash

  cross-compile-aarch64-build:
    <<: *cross-compile-aarch64-common
    command: /bin/bash -cl "mvn clean package -Plinux-aarch64 -DskipTests=true"
