version: "3"

services:

  runtime-setup:
    image: netty-io_uring:default
    build:
      context: .
      dockerfile: Dockerfile.centos

  common: &common
    image: netty-io_uring:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
    working_dir: /code

  test-leak:
    <<: *common
    command: /bin/bash -cl "./mvnw -Pleak clean test -Dio.netty.testsuite.badHost=netty.io -Dmaven.wagon.http.pool=false"

  test:
    <<: *common
    command: /bin/bash -cl "./mvnw clean test -Dio.netty.testsuite.badHost=netty.io -Dmaven.wagon.http.pool=false"

  build: 
    <<: *common
    command: /bin/bash -cl "./mvnw clean package -Dio.netty.testsuite.badHost=netty.io -Dmaven.wagon.http.pool=false"

  shell:
    <<: *common
    environment:
      - SANOTYPE_USER
      - SANOTYPE_PASSWORD
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash

  cross-compile-aarch64-runtime-setup:
    image: netty:cross_compile_aarch64
    build:
      context: .
      dockerfile: Dockerfile.cross_compile_aarch64
      args:
        gcc_version: "4.9-2016.02"

  cross-compile-aarch64-shell:
    image: netty:cross_compile_aarch64
    depends_on: [ cross-compile-aarch64-runtime-setup ]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash
    working_dir: /code

  cross-compile-aarch64-build:
    image: netty:cross_compile_aarch64
    depends_on: [ cross-compile-aarch64-runtime-setup ]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    command: /bin/bash -cl "./mvnw clean install -Plinux-aarch64"
    working_dir: /code
