name: Deploy snapshots

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '30 5 * * 1'  # At 05:30 on Monday, every Monday.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stage-snapshot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - setup: linux-x86_64
            docker-compose-build: "-f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml build"
            docker-compose-run: "-f docker/docker-compose.centos-6.yaml -f docker/docker-compose.centos-6.18.yaml run stage-snapshot"
          - setup: linux-aarch64
            docker-compose-build: "-f docker/docker-compose.centos-7.yaml build"
            docker-compose-run: "-f docker/docker-compose.centos-7.yaml run cross-compile-aarch64-stage-snapshot"
    name: stage-snapshot-${{ matrix.setup }}
    steps:
      - uses: actions/checkout@v2

      # Enable caching of Docker layers
      - uses: satackey/action-docker-layer-caching@v0.0.8
        env:
          docker-cache-name: staging-${{ matrix.setup }}-cache-docker
        continue-on-error: true
        with:
          key: ${{ runner.os }}-staging-${{ env.docker-cache-name }}-{hash}
          restore-keys: |
            ${{ runner.os }}-staging-${{ env.docker-cache-name }}-

      - name: Create local staging directory
        run: mkdir -p ~/local-staging

      - name: Build docker image
        run: docker-compose ${{ matrix.docker-compose-build }}

      - name: Stage snapshots to local staging directory
        run: docker-compose ${{ matrix.docker-compose-run }}

      - name: Upload local staging directory
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.setup }}-local-staging
          path: ~/local-staging

  deploy-staged-snapshots:
    runs-on: ubuntu-18.04
    # Wait until we have staged everything
    needs: stage-snapshot
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Cache .m2/repository
      - uses: actions/cache@v2
        env:
          cache-name: deploy-staging-cache-m2-repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-deploy-${{ env.cache-name }}-
            ${{ runner.os }}-deploy-

      # Setup some env to re-use later.
      - name: Prepare enviroment variables
        run: |
          echo "LOCAL_STAGING_DIR=$HOME/local-staging" >> $GITHUB_ENV

      # Hardcode the staging artifacts that need to be downloaded.
      # These must match the matrix setups. There is currently no way to pull this out of the config.
      - name: Download linux-aarch64 staging directory
        uses: actions/download-artifact@v2
        with:
          name: linux-aarch64-local-staging
          path: ~/linux-aarch64-local-staging

      - name: Download linux-x86_64 staging directory
        uses: actions/download-artifact@v2
        with:
          name: linux-x86_64-local-staging
          path: ~/linux-x86_64-local-staging

      - name: Merge staging repositories
        run: |
          mkdir -p ~/local-staging/deferred
          cat ~/linux-aarch64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
          cp -r ~/linux-aarch64-local-staging/deferred/* ~/local-staging/deferred/
          cat ~/linux-x86_64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
          cp -r ~/linux-x86_64-local-staging/deferred/* ~/local-staging/deferred/

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-snapshots",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - name: Deploy local staged artifacts
        run: mvn -B --file pom.xml org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged -DaltStagingDirectory=$LOCAL_STAGING_DIR